# This is a basic workflow to help you get started with Actions

name: GKE_Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dr" ]
  #pull_request:
   # branches: [ "main" ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      
      - name: google Auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set GCP Project ID
        run: gcloud config set project nifty-altar-394805
      
      - name: Set GKE Cluster
        run: gcloud container clusters get-credentials cluster-prod  cluster-dr --zone us-central1
     
      - name: Run build
        run: docker build -t  demo-wordpress .
        
      - name: image  tag
        run: |
          docker tag demo-wordpress sitharamaneesh/demo-wordpress
          #docker tag mariadb:10.5.8  sitharamaneesh/mariadb:10.5.8       
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sitharamaneesh
          password: sitharasarath
          
      - name: Docker push
        run: |
          docker push sitharamaneesh/demo-wordpress:latest
          #docker push sitharamaneesh/mariadb:10.5.8
          
      - name: deploy
        run: kubectl apply -f deployment.yaml


